### ISSUE TITLE
The FB <meta> tags are incorrect.

### ISSUE THREAD

**Issue by tsdubose** [rucwebdesign19/unit-1-The-Incredible-Red#1]
https://github.com/rucwebdesign19/unit-1-The-Incredible-Red/blob/b8510c07cc32ff59280568a1192efefad25fcdbd/chapter1.html#L10
Look up the syntax again and correct.

**Comment by The-Incredible-Red** [comment]
I have changed the meta tags to:
<meta property="og:title" content="A Tale Of Two Cities">
